name: CMake Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install CMake
        run: choco install cmake --version=3.21.0 --yes

      - name: Check out the code
        uses: actions/checkout@v2
        with:
          submodules: recursive 

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Configure CMake with Preset and vcpkg
        run: |
          cmake --preset vs2022-windows-vcpkg-release -DCMAKE_TOOLCHAIN_FILE=%CD%\vcpkg\scripts\buildsystems\vcpkg.cmake

      - name: Build with CMake in Release mode
        run: cmake --build build --config Release
