name: CMake Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure CMake with Preset
        run: cmake --preset vs2022-windows-vcpkg-release

      - name: Build with CMake in Release mode
        run: cmake --build build --config Release
